"""sprint14_compras_lealtad_sucursal

Revision ID: 280a7b5f4c0a
Revises: 70f7308be053
Create Date: 2026-04-15 10:37:39.263636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '280a7b5f4c0a'
down_revision: Union[str, Sequence[str], None] = '70f7308be053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sucursales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('codigo_postal', sa.String(length=5), nullable=True),
    sa.Column('lugar_expedicion', sa.String(length=5), nullable=True),
    sa.Column('es_matriz', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sucursales_codigo'), ['codigo'], unique=True)

    op.create_table('evaluaciones_proveedor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('periodo_inicio', sa.Date(), nullable=False),
    sa.Column('periodo_fin', sa.Date(), nullable=False),
    sa.Column('calidad_producto', sa.Integer(), nullable=False),
    sa.Column('puntualidad_entrega', sa.Integer(), nullable=False),
    sa.Column('precio_competitivo', sa.Integer(), nullable=False),
    sa.Column('atencion_servicio', sa.Integer(), nullable=False),
    sa.Column('calificacion_global', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('ordenes_evaluadas', sa.Integer(), nullable=False),
    sa.Column('entregas_a_tiempo', sa.Integer(), nullable=False),
    sa.Column('entregas_completas', sa.Integer(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluaciones_proveedor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluaciones_proveedor_proveedor_id'), ['proveedor_id'], unique=False)

    op.create_table('ordenes_compra',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('folio', sa.String(length=30), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('fecha_entrega_esperada', sa.Date(), nullable=True),
    sa.Column('fecha_recepcion', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('BORRADOR', 'ENVIADA', 'PARCIAL', 'RECIBIDA', 'CANCELADA', name='estadoordencompra'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ordenes_compra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ordenes_compra_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordenes_compra_folio'), ['folio'], unique=True)
        batch_op.create_index(batch_op.f('ix_ordenes_compra_proveedor_id'), ['proveedor_id'], unique=False)

    op.create_table('traspasos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('folio', sa.String(length=30), nullable=False),
    sa.Column('sucursal_origen_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_destino_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('SOLICITADO', 'EN_TRANSITO', 'RECIBIDO', 'CANCELADO', name='estadotraspaso'), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recibido_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_destino_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['sucursal_origen_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traspasos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traspasos_folio'), ['folio'], unique=True)

    op.create_table('cuentas_pagar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('orden_compra_id', sa.Integer(), nullable=True),
    sa.Column('concepto', sa.String(length=300), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monto_pagado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saldo_pendiente', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fecha_factura', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PARCIAL', 'PAGADA', 'VENCIDA', 'CANCELADA', name='estadocuentapagar'), nullable=False),
    sa.Column('numero_factura', sa.String(length=50), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['orden_compra_id'], ['ordenes_compra.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cuentas_pagar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cuentas_pagar_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_cuentas_pagar_fecha_vencimiento'), ['fecha_vencimiento'], unique=False)
        batch_op.create_index(batch_op.f('ix_cuentas_pagar_proveedor_id'), ['proveedor_id'], unique=False)

    op.create_table('cupones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('PORCENTAJE', 'MONTO_FIJO', 'PRODUCTO_GRATIS', 'PUNTOS_EXTRA', name='tipocupon'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('compra_minima', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('nivel_requerido', sa.Enum('BRONCE', 'PLATA', 'ORO', name='nivellealtad'), nullable=True),
    sa.Column('max_usos', sa.Integer(), nullable=False),
    sa.Column('usos_actuales', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVO', 'USADO', 'EXPIRADO', 'CANCELADO', name='estadocupon'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cupones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cupones_codigo'), ['codigo'], unique=True)

    op.create_table('detalles_orden_compra',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_solicitada', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cantidad_recibida', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalles_traspaso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('traspaso_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_enviada', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cantidad_recibida', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['traspaso_id'], ['traspasos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_puntos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.Column('saldo_anterior', sa.Integer(), nullable=False),
    sa.Column('saldo_nuevo', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historial_puntos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historial_puntos_cliente_id'), ['cliente_id'], unique=False)

    op.create_table('inventario_sucursal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('stock_actual', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventario_sucursal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventario_sucursal_producto_id'), ['producto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventario_sucursal_sucursal_id'), ['sucursal_id'], unique=False)

    op.create_table('cupones_cliente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cupon_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('fecha_uso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.Column('asignado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['cupon_id'], ['cupones.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos_cuentas_pagar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas_pagar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nivel_lealtad', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('puntos_totales_historicos', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fecha_cumpleanos', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('tarjeta_qr', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('notas', sa.Text(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_clientes_rfc'), ['rfc'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_rfc'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('notas')
        batch_op.drop_column('tarjeta_qr')
        batch_op.drop_column('fecha_cumpleanos')
        batch_op.drop_column('puntos_totales_historicos')
        batch_op.drop_column('nivel_lealtad')

    op.drop_table('pagos_cuentas_pagar')
    op.drop_table('cupones_cliente')
    with op.batch_alter_table('inventario_sucursal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventario_sucursal_sucursal_id'))
        batch_op.drop_index(batch_op.f('ix_inventario_sucursal_producto_id'))

    op.drop_table('inventario_sucursal')
    with op.batch_alter_table('historial_puntos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historial_puntos_cliente_id'))

    op.drop_table('historial_puntos')
    op.drop_table('detalles_traspaso')
    op.drop_table('detalles_orden_compra')
    with op.batch_alter_table('cupones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cupones_codigo'))

    op.drop_table('cupones')
    with op.batch_alter_table('cuentas_pagar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cuentas_pagar_proveedor_id'))
        batch_op.drop_index(batch_op.f('ix_cuentas_pagar_fecha_vencimiento'))
        batch_op.drop_index(batch_op.f('ix_cuentas_pagar_estado'))

    op.drop_table('cuentas_pagar')
    with op.batch_alter_table('traspasos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traspasos_folio'))

    op.drop_table('traspasos')
    with op.batch_alter_table('ordenes_compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordenes_compra_proveedor_id'))
        batch_op.drop_index(batch_op.f('ix_ordenes_compra_folio'))
        batch_op.drop_index(batch_op.f('ix_ordenes_compra_estado'))

    op.drop_table('ordenes_compra')
    with op.batch_alter_table('evaluaciones_proveedor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluaciones_proveedor_proveedor_id'))

    op.drop_table('evaluaciones_proveedor')
    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sucursales_codigo'))

    op.drop_table('sucursales')
    # ### end Alembic commands ###
