"""sprint14_compras_lealtad_sucursal

Revision ID: 280a7b5f4c0a
Revises: 70f7308be053
Create Date: 2026-04-15 10:37:39.263636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '280a7b5f4c0a'
down_revision: Union[str, Sequence[str], None] = '70f7308be053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(table_name: str) -> bool:
    return table_name in inspect(op.get_bind()).get_table_names()


def _column_exists(table_name: str, column_name: str) -> bool:
    if not _table_exists(table_name):
        return False
    return column_name in {column["name"] for column in inspect(op.get_bind()).get_columns(table_name)}


def _index_exists(table_name: str, index_name: str) -> bool:
    if not _table_exists(table_name):
        return False
    return index_name in {index["name"] for index in inspect(op.get_bind()).get_indexes(table_name)}


def _bootstrap_current_schema() -> None:
    from app.core.database import Base
    import app.models  # noqa: F401

    Base.metadata.create_all(bind=op.get_bind(), checkfirst=True)


def upgrade() -> None:
    """Upgrade schema."""
    _bootstrap_current_schema()
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        if not _column_exists('clientes', 'nivel_lealtad'):
            batch_op.add_column(sa.Column('nivel_lealtad', sa.String(length=20), nullable=False, server_default='bronce'))
        if not _column_exists('clientes', 'puntos_totales_historicos'):
            batch_op.add_column(sa.Column('puntos_totales_historicos', sa.Integer(), nullable=False, server_default='0'))
        if not _column_exists('clientes', 'fecha_cumpleanos'):
            batch_op.add_column(sa.Column('fecha_cumpleanos', sa.Date(), nullable=True))
        if not _column_exists('clientes', 'tarjeta_qr'):
            batch_op.add_column(sa.Column('tarjeta_qr', sa.String(length=100), nullable=True))
        if not _column_exists('clientes', 'notas'):
            batch_op.add_column(sa.Column('notas', sa.Text(), nullable=True))
        if not _index_exists('clientes', 'ix_clientes_rfc'):
            batch_op.create_index(batch_op.f('ix_clientes_rfc'), ['rfc'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_rfc'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('notas')
        batch_op.drop_column('tarjeta_qr')
        batch_op.drop_column('fecha_cumpleanos')
        batch_op.drop_column('puntos_totales_historicos')
        batch_op.drop_column('nivel_lealtad')

    op.drop_table('pagos_cuentas_pagar')
    op.drop_table('cupones_cliente')
    with op.batch_alter_table('inventario_sucursal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventario_sucursal_sucursal_id'))
        batch_op.drop_index(batch_op.f('ix_inventario_sucursal_producto_id'))

    op.drop_table('inventario_sucursal')
    with op.batch_alter_table('historial_puntos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historial_puntos_cliente_id'))

    op.drop_table('historial_puntos')
    op.drop_table('detalles_traspaso')
    op.drop_table('detalles_orden_compra')
    with op.batch_alter_table('cupones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cupones_codigo'))

    op.drop_table('cupones')
    with op.batch_alter_table('cuentas_pagar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cuentas_pagar_proveedor_id'))
        batch_op.drop_index(batch_op.f('ix_cuentas_pagar_fecha_vencimiento'))
        batch_op.drop_index(batch_op.f('ix_cuentas_pagar_estado'))

    op.drop_table('cuentas_pagar')
    with op.batch_alter_table('traspasos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traspasos_folio'))

    op.drop_table('traspasos')
    with op.batch_alter_table('ordenes_compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordenes_compra_proveedor_id'))
        batch_op.drop_index(batch_op.f('ix_ordenes_compra_folio'))
        batch_op.drop_index(batch_op.f('ix_ordenes_compra_estado'))

    op.drop_table('ordenes_compra')
    with op.batch_alter_table('evaluaciones_proveedor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluaciones_proveedor_proveedor_id'))

    op.drop_table('evaluaciones_proveedor')
    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sucursales_codigo'))

    op.drop_table('sucursales')
    # ### end Alembic commands ###
