"""initial schema

Revision ID: 468f170cd373
Revises: 
Create Date: 2026-04-14 04:31:44.848752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '468f170cd373'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(table_name: str) -> bool:
    return table_name in inspect(op.get_bind()).get_table_names()


def _column_exists(table_name: str, column_name: str) -> bool:
    if not _table_exists(table_name):
        return False
    return column_name in {column["name"] for column in inspect(op.get_bind()).get_columns(table_name)}


def _index_exists(table_name: str, index_name: str) -> bool:
    if not _table_exists(table_name):
        return False
    return index_name in {index["name"] for index in inspect(op.get_bind()).get_indexes(table_name)}


def _unique_exists(table_name: str, constraint_name: str) -> bool:
    if not _table_exists(table_name):
        return False
    return constraint_name in {
        constraint["name"] for constraint in inspect(op.get_bind()).get_unique_constraints(table_name)
    }


def upgrade() -> None:
    """Upgrade schema."""
    # This project originally used Base.metadata.create_all before Alembic had a
    # real baseline migration. Bootstrap missing tables first so a clean database
    # can be migrated to head without falling back at application startup.
    from app.core.database import Base
    import app.models  # noqa: F401

    Base.metadata.create_all(bind=op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    if _table_exists('cfdi_comprobantes') and not _unique_exists('cfdi_comprobantes', 'uq_cfdi_serie_folio'):
        with op.batch_alter_table('cfdi_comprobantes', schema=None) as batch_op:
            batch_op.create_unique_constraint('uq_cfdi_serie_folio', ['serie', 'folio'])

    with op.batch_alter_table('cortes_caja', schema=None) as batch_op:
        if not _column_exists('cortes_caja', 'total_ventas_clip'):
            batch_op.add_column(sa.Column('total_ventas_clip', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))
        if not _column_exists('cortes_caja', 'total_ventas_bbva'):
            batch_op.add_column(sa.Column('total_ventas_bbva', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))

    with op.batch_alter_table('productos', schema=None) as batch_op:
        if not _column_exists('productos', 'imagen'):
            batch_op.add_column(sa.Column('imagen', sa.Text(), nullable=True))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        if not _column_exists('usuarios', 'permisos_modulos'):
            batch_op.add_column(sa.Column('permisos_modulos', sa.Text(), nullable=True))

    with op.batch_alter_table('ventas', schema=None) as batch_op:
        if not _column_exists('ventas', 'terminal'):
            batch_op.add_column(sa.Column('terminal', sa.Enum('EFECTIVO', 'CLIP', 'BBVA', name='terminalpago'), nullable=False, server_default='EFECTIVO'))
        if not _index_exists('ventas', 'ix_ventas_folio'):
            batch_op.create_index('ix_ventas_folio', ['folio'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_column('terminal')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('permisos_modulos')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('imagen')

    with op.batch_alter_table('cortes_caja', schema=None) as batch_op:
        batch_op.drop_column('total_ventas_bbva')
        batch_op.drop_column('total_ventas_clip')

    with op.batch_alter_table('cfdi_comprobantes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_cfdi_serie_folio', type_='unique')

    # ### end Alembic commands ###
