"""initial schema

Revision ID: 468f170cd373
Revises: 
Create Date: 2026-04-14 04:31:44.848752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468f170cd373'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cfdi_comprobantes', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_cfdi_serie_folio', ['serie', 'folio'])

    with op.batch_alter_table('cortes_caja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_ventas_clip', sa.Numeric(precision=14, scale=2), nullable=False))
        batch_op.add_column(sa.Column('total_ventas_bbva', sa.Numeric(precision=14, scale=2), nullable=False))

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.Text(), nullable=True))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permisos_modulos', sa.Text(), nullable=True))

    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terminal', sa.Enum('EFECTIVO', 'CLIP', 'BBVA', name='terminalpago'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_column('terminal')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('permisos_modulos')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('imagen')

    with op.batch_alter_table('cortes_caja', schema=None) as batch_op:
        batch_op.drop_column('total_ventas_bbva')
        batch_op.drop_column('total_ventas_clip')

    with op.batch_alter_table('cfdi_comprobantes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_cfdi_serie_folio', type_='unique')

    # ### end Alembic commands ###
