"""sprint15_merma_fiscal_crm_calidad_auditoria

Revision ID: 5866f5d625db
Revises: 280a7b5f4c0a
Create Date: 2026-04-15 11:31:02.075270

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '5866f5d625db'
down_revision: Union[str, Sequence[str], None] = '280a7b5f4c0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _bootstrap_current_schema() -> None:
    from app.core.database import Base
    import app.models  # noqa: F401

    Base.metadata.create_all(bind=op.get_bind(), checkfirst=True)


def upgrade() -> None:
    """Upgrade schema."""
    _bootstrap_current_schema()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trazabilidad_lotes')
    op.drop_table('checklists_calidad')
    op.drop_table('registros_merma')
    op.drop_table('alertas_recall')
    with op.batch_alter_table('encuestas_satisfaccion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_encuestas_satisfaccion_cliente_id'))

    op.drop_table('encuestas_satisfaccion')
    with op.batch_alter_table('log_auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_auditoria_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_log_auditoria_creado_en'))

    op.drop_table('log_auditoria')
    with op.batch_alter_table('interacciones_cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interacciones_cliente_cliente_id'))

    op.drop_table('interacciones_cliente')
    op.drop_table('campanas')
    op.drop_table('configuracion_seguridad')
    # ### end Alembic commands ###
