"""sprint15_merma_fiscal_crm_calidad_auditoria

Revision ID: 5866f5d625db
Revises: 280a7b5f4c0a
Create Date: 2026-04-15 11:31:02.075270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5866f5d625db'
down_revision: Union[str, Sequence[str], None] = '280a7b5f4c0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_seguridad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('campanas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('segmento_objetivo', sa.String(length=20), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('enviados', sa.Integer(), nullable=False),
    sa.Column('abiertos', sa.Integer(), nullable=False),
    sa.Column('conversiones', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interacciones_cliente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('canal', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interacciones_cliente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interacciones_cliente_cliente_id'), ['cliente_id'], unique=False)

    op.create_table('log_auditoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nombre', sa.String(length=200), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('modulo', sa.String(length=100), nullable=False),
    sa.Column('entidad', sa.String(length=100), nullable=True),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('datos_anteriores', sa.Text(), nullable=True),
    sa.Column('datos_nuevos', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_auditoria_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_auditoria_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('encuestas_satisfaccion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.Column('calificacion', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('encuestas_satisfaccion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_encuestas_satisfaccion_cliente_id'), ['cliente_id'], unique=False)

    op.create_table('alertas_recall',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lote_ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('severidad', sa.String(length=20), nullable=False),
    sa.Column('productos_afectados', sa.Text(), nullable=False),
    sa.Column('acciones_tomadas', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('reportado_por', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resuelto_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lote_ingrediente_id'], ['lotes_ingrediente.id'], ),
    sa.ForeignKeyConstraint(['reportado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_merma',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('ingrediente_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('CADUCIDAD', 'PRODUCCION', 'DANO', 'DEVOLUCION', 'OTRO', name='tipomerma'), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unidad_medida', sa.String(length=20), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('costo_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('fecha_merma', sa.Date(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_ingrediente.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklists_calidad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orden_produccion_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inspeccion', sa.Date(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'APROBADO', 'RECHAZADO', 'OBSERVACIONES', name='estadoinspeccion'), nullable=False),
    sa.Column('apariencia', sa.Integer(), nullable=True),
    sa.Column('textura', sa.Integer(), nullable=True),
    sa.Column('sabor', sa.Integer(), nullable=True),
    sa.Column('peso_correcto', sa.Boolean(), nullable=False),
    sa.Column('empaque_correcto', sa.Boolean(), nullable=False),
    sa.Column('temperatura_correcta', sa.Boolean(), nullable=False),
    sa.Column('peso_muestra', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('temperatura_muestra', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('foto_url', sa.Text(), nullable=True),
    sa.Column('calificacion_global', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspector_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['orden_produccion_id'], ['ordenes_produccion.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trazabilidad_lotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lote_ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('orden_produccion_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('cantidad_usada', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('fecha_uso', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lote_ingrediente_id'], ['lotes_ingrediente.id'], ),
    sa.ForeignKeyConstraint(['orden_produccion_id'], ['ordenes_produccion.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trazabilidad_lotes')
    op.drop_table('checklists_calidad')
    op.drop_table('registros_merma')
    op.drop_table('alertas_recall')
    with op.batch_alter_table('encuestas_satisfaccion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_encuestas_satisfaccion_cliente_id'))

    op.drop_table('encuestas_satisfaccion')
    with op.batch_alter_table('log_auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_auditoria_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_log_auditoria_creado_en'))

    op.drop_table('log_auditoria')
    with op.batch_alter_table('interacciones_cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interacciones_cliente_cliente_id'))

    op.drop_table('interacciones_cliente')
    op.drop_table('campanas')
    op.drop_table('configuracion_seguridad')
    # ### end Alembic commands ###
